fNum = input("What is the first number? ")
sNum = input("What is the second number? ")
print(fNum,"+",sNum,"= %d" % (int(fNum) + int(sNum)))
print(fNum,"-",sNum,"= %d" % (int(fNum) - int(sNum)))
print(fNum,"*",sNum,"= %d" % (int(fNum) * int(sNum)))
print(fNum,"/",sNum,"= %d" % (int(fNum) / int(sNum)))